Move access monitoring commands to OSS tctl
The `tctl audit` family of commands are now in OSS, but will fail
with an error if the auth server does not have an enterprise license:

    ❯ tctl audit report ls
    ERROR: Access Monitoring requires a Teleport Enterprise Auth Server.

Updates #36457