[v16] Update roles.mdx with clarity around users and roles visibility (#59203)
* Update roles.mdx with clarity around users and roles visibility

based on customer feedback, adding clarity around why a user can see their own roles and user information remotely with `tctl` even when explicitly denied

https://github.com/gravitational/teleport/blob/642be764ce5395e7da312f9a839935862ea03425/lib/auth/auth_with_roles.go#L4778-L4790

~~~
paulschisa@Pauls-MacBook-Pro ~ % tctl get roles/test-role
kind: role
metadata:
  description: Test role equivalent to Entra group placeholder roles
  labels:
    teleport.internal/downgraded: Role V8 is only supported from the client version
      "18.0.0-aa" and above.Access to SAML IdP will be disabled.
    test-role: "true"
  name: test-role
  revision: ab3f6385-07b4-40b7-8496-a396a89b0fbe
spec:
  allow:
  deny:
    rules:
    - resources:
      - role
      verbs:
      - '*'
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    device_trust_mode: required-for-humans
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: false
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    record_session:
      default: strict
      desktop: true
    ssh_file_copy: true
version: v7
paulschisa@Pauls-MacBook-Pro ~ % tctl get roles
ERROR: access denied to perform action "list" on "role", access denied to perform action "read" on "role"

paulschisa@Pauls-MacBook-Pro ~ % tctl get roles/access
ERROR: access denied to perform action "read" on "role"

paulschisa@Pauls-MacBook-Pro ~ % tctl get roles/test-role
kind: role
metadata:
  description: Test role equivalent to Entra group placeholder roles
  labels:
    teleport.internal/downgraded: Role V8 is only supported from the client version
      "18.0.0-aa" and above.Access to SAML IdP will be disabled.
    test-role: "true"
  name: test-role
  revision: ab3f6385-07b4-40b7-8496-a396a89b0fbe
spec:
  allow:
    kubernetes_groups:
    - teleport-viewers
    kubernetes_labels:
      cdf: "true"
  deny:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: '*'
      verbs:
      - '*'
    rules:
    - resources:
      - role
      verbs:
      - '*'
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    device_trust_mode: required-for-humans
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: false
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    record_session:
      default: strict
      desktop: true
    ssh_file_copy: true
version: v7
paulschisa@Pauls-MacBook-Pro ~ % tctl get roles
ERROR: access denied to perform action "list" on "role", access denied to perform action "read" on "role"

paulschisa@Pauls-MacBook-Pro ~ % tctl get roles/access
ERROR: access denied to perform action "read" on "role"
~~~

* Update docs/pages/reference/access-controls/roles.mdx

Co-authored-by: Paul Gottschling <paul.gottschling@goteleport.com>

* Update roles.mdx

* Update roles.mdx

---------

Co-authored-by: Paul Gottschling <paul.gottschling@goteleport.com>