pr; Don't replace $$ with $
A `$` is not valid in a role name, so we do not need to replace `$$` in
an attribute role mapping when checking if the role exists:

    $ tctl create r/role-test-apps.yaml
    ERROR: special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs: "/roles/test$apps/params"