Fix web UI host resolution
Web sessions were dialing with the sever hostname in cases where
the server UUID was known and should have been used which resulted
in #19415. All sessions launched via the "Connect" button from the
UI are guaranteed to use the server UUID. Manual connections via
the UI attempt find a matching host and use the UUID but may fallback
to using the hostname/ip instead if multiple matches are found.

When resolving servers by hostname or address `ListResources` is
now used directly to populate the `SearchKeywords` field to limit
the number of servers returned to only those fuzzily matching the
server. Prior to this **all** servers in the cluster were fetched
and filtered out by the web api.

The error displayed when ambiguous hosts are found has also been
improved changed from:

```shell
disconnected
err-node-is-ambiguous
```

to the following which more closely mirrors the error returned by
`tsh`:

```shell
disconnected
error: ambiguous host could match multiple nodes

Hint: try addressing the node by unique id (ex: user@node-id)
```

Closes #19415