Deflake HSM integration tests
TestHSMDualAuthRotation intermittently failed in CI with a spurious
error out of C_GenerateKeyPair:

    Failed to start Teleport instance
    error: generating ECDSAP256 key
        pkcs11: 0x5: CKR_GENERAL_ERROR

SoftHSM's file object store is not safe for concurrent use by multiple
threads of a single process. While one thread is generating keypairs,
another thread can read the half-written object, wiping the new
object's in-memory attributes.

This issue can manifest in any HSM test, because Teleport's auth service
initialization initializes all CAs concurrently. It just happens to show
up most frequently in TestHSMDualAuthRotation because that test does the
most HSM Work.

This is not an issue in production because:
- SoftHSM is not used in production
- We don't run multiple auth servers in a single process in production

The fix covers two different types of concurrent access:
1. Two different auth servers doing concurrent access.
   This is fixed by giving each auth server its own SoftHSM token.
2. One auth server doing concurrent access.
   This is fixed by setting MaxSessions, effectively serializing
   the HSM operations.

Closes #65482