[v15] Bump helm.sh/helm/v3 to 3.17.3 (#54036)
* [v16] Bump helm.sh/helm/v3 to 3.17.3 (#54035)

* Bump helm.sh/helm/v3 from 3.17.2 to 3.17.3

* kube: prepare for k8s v1.32.0 deps (#51798)

* kube: prepare for k8s v1.32.0 deps

This PR updates the Kubernetes proxy and server mock to align with the default content-type change introduced in version v1.32.0 of client-go.

In `k8s.io/client-go`, the client's default content type was changed from `application/json` to `application/vnd.kubernetes.protobuf`.

Kube mock was not equipped to decode protobuf messages, leading to multiple failures.
Additionally, there was a typo where both request content-types were inconsistently mixed.

Signed-off-by: Tiago Silva <tiago.silva@goteleport.com>

* handle review comments

---------

Signed-off-by: Tiago Silva <tiago.silva@goteleport.com>

* Bump helm.sh/helm/v3 from 3.17.2 to 3.17.3 in /build.assets/tooling (#53915)

Bumps [helm.sh/helm/v3](https://github.com/helm/helm) from 3.17.2 to 3.17.3.
- [Release notes](https://github.com/helm/helm/releases)
- [Commits](https://github.com/helm/helm/compare/v3.17.2...v3.17.3)

---
updated-dependencies:
- dependency-name: helm.sh/helm/v3
  dependency-version: 3.17.3
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update `sigs.k8s.io/controller-runtime` to v0.20.4

Doing `make -C integrations test-lib` was failing with

```
marcodinis@MarcoM3 ~/s/teleport (marco/v16/backport_53916)> make -C integrations test-lib
go test ./lib/...
ok      github.com/gravitational/teleport/integrations/lib      (cached)
ok      github.com/gravitational/teleport/integrations/lib/backoff      (cached)
ok      github.com/gravitational/teleport/integrations/lib/credentials  (cached)
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.1/pkg/internal/controller/controller.go:103:9: not enough arguments in call to fn
        have (interface{})
        want (context.Context, interface{})
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.1/pkg/webhook/admission/webhook.go:158:9: not enough arguments in call to fn
        have (interface{})
        want (context.Context, interface{})
```

* disable name validation for tests to allow re-using the same name between tests

---------

Signed-off-by: Tiago Silva <tiago.silva@goteleport.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Tiago Silva <tiago.silva@goteleport.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* nolint:staticcheck SA1019 for grpc package

* remove lib/observability/tracing TestNewExporter/connection_timeout (same as v16)

* change lib/observability/tracing TestNewClient (same as v16)

* Revert "nolint:staticcheck SA1019 for grpc package"

This reverts commit 3413b51ab21afe9db40db2dfca32f1a717f5b2d9.

* chore: Bump google.golang.org/grpc to v1.64.0 (#41774)

* chore: Bump google.golang.org/grpc to v1.64.0

* Add exceptions for existing deprecated Dial options

* Add exception for integrations/terraform

---------

Signed-off-by: Tiago Silva <tiago.silva@goteleport.com>
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Tiago Silva <tiago.silva@goteleport.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Alan Parra <alan.parra@goteleport.com>