ci: Pass secrets from post-release to update-ami-ids (#30020)
Add a `secrets: inherit` field to `post-release.yaml` so that when
calling `update-ami-ids.yaml` it can see the secrets. It is currently
failing with:

    Error: Input required and not supplied: private_key

as the repo secrets are not available.