Revert cloud.google.com/go/spanner to 1.83.0
The update to 1.85.0 brought changes which were causing tests to
fail and should be remediated in a separate change.

```
 {"timestamp":"2025-09-04T14:10:31Z","level":"debug","caller":"spanner/interceptors.go:60","message":"failed to handle Spanner RPC","component":"db:service","id":"5a639394-c212-41b5-92e8-77e8e869a6dc","db":"my-spanner","full_method":"/google.spanner.v1.Spanner/CreateSession","error":"rpc error: code = Unimplemented desc = method CreateSession not implemented"}
{"timestamp":"2025-09-04T14:10:31Z","level":"info","caller":":0","message":"Multiplexed session is not enabled on this project, continuing with regular sessions"}
{"timestamp":"2025-09-04T14:10:31Z","level":"info","caller":"eventstest/channel.go:46","message":"EmitAuditEvent","component":"channel_emitter","event_type":"db.session.spanner.rpc","event_code":"TSPN001I"}
{"timestamp":"2025-09-04T14:10:31Z","level":"info","caller":"db/auth_test.go:356","message":"Generating Cloud Spanner auth token source","component":"auth:test","database_user":"admin@project-id.iam.gserviceaccount.com"}
    spanner_test.go:307:
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/spanner_test.go:307
        	Error:      	Not equal:
        	            	expected: "ExecuteStreamingSql"
        	            	actual  : "CreateSession"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-ExecuteStreamingSql
        	            	+CreateSession
        	Test:       	TestAuditSpanner/successful_flow
```