Allow unknown fields when unmarshaling types.MFADevice (#25437)
There was a backward incompatible change introduce in
https://github.com/gravitational/teleport/pull/25238 that was preventing mfa devices from being
unmarshalled due to an unknown field:

```
tctl users reset norbert
ERROR: rpc error: code = Unknown desc = unknown field "credentialRpId" in types.WebauthnDevice
```

The custom `json.Unmarshaler` implemented by `types.MFADevice` did
not initialize the protojson decoder to allow unknown fields. This
prevented any reads of `types.MFADevice` from a backend that was
upgraded and then downgraded.