Never use `--tlsUseSystemCA` and `--tlsCAFile` together with `mongosh` (#12361)
`mongosh` doesn't support `--tlsUseSystemCA` and `--tlsCAFile` combination passed together and fails CA validation with error when the required CA is not in the system store 
```
MongoServerSelectionError: unable to verify the first certificate
```
This change makes those flags mutually exclusive.