Removed `TestProxyReverseTunnel`.
`TestProxyReverseTunnel` has been consistently failing with the following errors.

--- FAIL: TestProxyReverseTunnel (11.76s)
    sshserver_test.go:1127:
        	Error Trace:	sshserver_test.go:1127
        	Error:      	Received unexpected error:
        	            	timeout waiting for announce to be sent
        	Test:       	TestProxyReverseTunnel
FAIL
FAIL	github.com/gravitational/teleport/lib/srv/regular	68.907s

--- FAIL: TestProxyReverseTunnel (23.43s)
    assertion_compare.go:332:
        	Error Trace:	sshserver_test.go:1144
        	Error:      	"5.775333527" is not less than "5"
        	Test:       	TestProxyReverseTunnel
        	Messages:   	[]
FAIL
FAIL	github.com/gravitational/teleport/lib/srv/regular	96.861s

These both appear to be timing related. By removing `t.Parallel()` or
increasing the timeouts it was possible to stabilize this test and have it
consistently pass. However, looking at what `TestProxyReverseTunnel` actually
tested, I don't think it can actually be removed completely. I've outlined
what it tested and why this is no longer necessary and why we should remove it.

* Reverse tunnels can be established

This test was written prior to integration tests existing. Teleport now has
integration tests that are more extensive, robust, and stable which cover
reverse tunnel functionality like `TwoClustersProxy`, `TwoClustersTunnel`, and
`TrustedTunnelNode`. The only thing they were missing that
`TestProxyReverseTunnel` had was checking `LastConnected` time. This PR has
been updated to add that to integration tests.

* Connectivity can be established over reverse tunnels

Similar to the above, we have more extensive, robust, and stable integration
test coverage for establishing connectivity over a reverse tunnel now.

The only bit of functionality that integration don't appear to have is
connecting by DNS name _and_ IP address at sshserver_test.go#L1066-L1067.
However, we do now have a dedicated unit test for this in
`TestProxySubsys_getMatchingServer`.

* Labels are synchronized

While this test does schenonize dynamic labels, it never actually checks if
they were synchronized correctly. That functionality was removed many years
ago in https://github.com/gravitational/teleport/pull/250.

We do now have unit test coverage for dynamic labels at
lib/labels/labels_test.go.