[v18] Bump Go to 1.25.7 (#63539)
* chore: Bump Go to 1.25.7

* Fix synctest bug with waitgroups
```
=== Failed
=== FAIL: lib/srv/discovery TestDiscoveryServerEKS (unknown)
fatal error: sync: WaitGroup.Add called from multiple synctest bubbles
```

The failure stems from a bug in Go 1.25 and is a result of loading
aws configs which internally use a sync.WaitGroup. This can be worked
around in the short term by mocking out the aws.Config since the test
is configured to use a mock eks client anyway. Other tests may still
run into this issue until Go 1.25.2 - though our relatively small number
of synctest usage at this point may limit our exposure to said bug.

* Lazily unmount cgroups
Adds the MNT_DETACH flag to the cgroups unmount call to workaround
issues stemming from a behavior chagne in Go 1.25 to support
automatically setting GOMAXPROCS. In doing so the Go runtime
interacts with cgroups to determine what limits should be applied
which interferes with our ability to clean up.

Fixes #58879.

* chore: Bump golangci-lint to v2.7.2 (#62066)

* chore: Bump golangci-lint to v2.7.2

* Update e/ reference

* Fix require.IsType issues

* Reverse require.Equal

* Simplify testWebsockets

* Fix TestCreateResources

* Remove trace.Unwrap

---------

Co-authored-by: Alan Parra <12500300+codingllama@users.noreply.github.com>