[docs] Fixes ACM helm example (#29454)
Prior to this change, running the example as written would result
in the followinmg error:

```
Error: INSTALLATION FAILED: execution error at (teleport-cluster/templates/proxy/service.yaml:5:6):
proxy.service.type must not be LoadBalancer when using an ingress - any load balancer should be
provisioned by your ingress controller. Set proxy.service.type=ClusterIP instead
```

This patch adds that change to the example cluster configuration
helm values.