Fix flaky GCP test (#65988)
A last minute change introduced in response to Codex feedback on #65910
introduced some flakiness:

   handler_test.go:148:
        	Error Trace:	/__w/teleport/teleport/lib/srv/app/gcp/handler_test.go:148
        	            				/__w/teleport/teleport/lib/srv/app/gcp/handler_test.go:167
        	Error:      	Target error should be in err chain:
        	            	expected: "context canceled"
        	            	in chain: "fncache permanently closed"
        	            		"fncache permanently closed"
        	Test:       	TestHandler_getToken/context_cancel

Use the test's context for the FnCache so it remains running for the
duration of the test.