Encode the runtime arch in all centos7 buildbox images
This was partially done before, but it was missed in images.mk, which
resulted in builder errors when images.mk data was used on its own.
This resulted in errors like the following:

  Error: buildx failed with: ERROR: failed to solve: ghcr.io/gravitational/teleport-buildbox-centos7:teleport16:
    ghcr.io/gravitational/teleport-buildbox-centos7:teleport16: not found