Update install-hardened.sh
This fixes a new issue where running the command `python3 -m venv /opt/certbot` on AL2023 minimal results in non zero-return:

```
Error: Command '['/opt/certbot/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

Here is further output when that command is run manually:

```
/opt/certbot/bin/python3: Error while finding module specification for 'ensurepip.__main__' (ImportError: cannot import name '_bundled' from partially initialized module 'ensurepip' (most likely due to a circular import) (/usr/lib64/python3.9/ensurepip/__init__.py))
```

Installing via AWS' certbot + certbot-dns-route53 package resolves the issue