docs: Flip Github connector examples for OSS vs Commercial
The Github connector examples in the docs were switched around.

Trying to create a Github connector with `api_endpoint_url` or `endpoint_url` set when using Teleport Community Edition results in an error:

```
[ec2-user@teleport ~]$ sudo /usr/local/bin/tctl create -f github.yaml
ERROR: this feature requires Teleport Enterprise
```

Setting both these values to empty strings causes creation to succeed.

Reported on Slack.