Prevent running flaky test detector on dependabot PRs (#3210)
Since dependabot is seen as an external contributor it does not
have the required permissions to generate the required github app
token. This results in the workflow always failing with the
following error:

```
/__w/_actions/actions/create-github-app-token/v1/dist/main.cjs:10482
  throw new Error("Input required and not supplied: app-id");
  ^

Error: Input required and not supplied: app-id
    at Object.<anonymous> (/__w/_actions/actions/create-github-app-token/v1/dist/main.cjs:10482:9)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
```

OSS never runs into this problem because there is a bypass workflow
which is always triggered. Instead of adding a bypass here the
workflow is onlyl run if the branch is not prefixed with
`dependabot/` in a similar manner to a number of workflows in OSS.

Source-commit: gravitational/teleport.e@0468bdbd63ac10ebc5910b504564a57ef65de742
Source-pull-requests: gravitational/teleport.e#3210